#!/usr/bin/env node
/* Focused tool-sheet smoke check. Uses only a synthetic native bridge. */
const {chromium}=require('playwright');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),web=path.join(root,'app/src/main/assets/web'),out=path.join(root,'artifacts/ui-redesign/after');fs.mkdirSync(out,{recursive:true});
const state={ready:true,busy:false,permissions:'workspace-write',status:'Connected',threadId:'qa',cwd:'/workspace',workspace:{selected:true,key:'qa-project',name:'QA project'},projects:[{key:'qa-project',name:'QA project',available:true}],sessions:[],account:{type:'chatgpt',email:'qa@example.test'},models:[],messages:[]};
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.MOBILE_CODEX_BROWSER_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});const context=await browser.newContext({viewport:{width:393,height:852}}),page=await context.newPage(),calls=[];
 try { await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!=='https://appassets.androidplatform.net')return route.abort();const f=path.resolve(web,'.'+u.pathname);return fs.existsSync(f)&&f.startsWith(web+path.sep)?route.fulfill({path:f}):route.fulfill({status:404,body:''});});
  await page.addInitScript(({state})=>{window.__qaState=state;window.__calls=[];window.Native={locale:()=>JSON.stringify({choice:'en',systemLanguage:'en'}),postMessage(raw){const m=JSON.parse(raw);window.__calls.push(m);let result={};if(m.action==='state')result=window.__qaState;if(m.action==='files.list')result={entries:[]};if(m.action==='changes.list')result={entries:[]};if(m.action==='recovery.list')result={entries:[]};if(m.action==='rpc')result={data:[],marketplaces:[]};setTimeout(()=>window.mobileCodexEvent('response',{id:m.id,result}),0);}};},{state});
  await page.goto('https://appassets.androidplatform.net/index.html');await page.waitForSelector('#show-tools');await page.waitForTimeout(120);
  await page.locator('.topbar .sidebar-toggle').click();await page.locator('#show-tools').click();
  const actions=[['show-files','file-panel','files.list'],['show-terminal','terminal-dialog',null],['show-tools-panel','tools-dialog','rpc'],['show-changes','changes-dialog','changes.list'],['show-recovery','recovery-dialog','recovery.list']];
  const results=[];
  for(const [id,dialog,action] of actions){if(await page.locator('#tool-menu-dialog').isVisible()) { await page.locator('#tool-menu-dialog [data-close="tool-menu-dialog"]').last().click();await page.waitForTimeout(30); } if(!(await page.evaluate(()=>document.body.classList.contains('sidebar-open')))) await page.locator('.topbar .sidebar-toggle').click();await page.locator('#show-tools').click();await page.locator('#tool-menu-dialog').waitFor({state:'visible'});await page.locator('#'+id).click();await page.waitForTimeout(120);assert.equal(await page.locator('#'+dialog).isVisible(),true,`${id} opens ${dialog}`);if(action)assert.ok((await page.evaluate(a=>window.__calls.some(call=>call.action===a),action)),`${id} invokes ${action}`);results.push({id,dialog,action,opened:true});if(dialog==='file-panel')await page.locator('#file-close').click();else await page.locator('#'+dialog+' [data-close="'+dialog+'"]').last().click();}
  await page.locator('.topbar .sidebar-toggle').click();await page.screenshot({path:path.join(out,'tool-menu-393-en.png')});
  fs.writeFileSync(path.join(out,'tool-menu-results.json'),JSON.stringify({sourceTimestamp:new Date().toISOString(),viewport:{width:393,height:852},results,assertions:'all five tool actions opened their real destination and invoked their native route'},null,2));console.log(JSON.stringify(results));
 } finally {await context.close();await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
